#!/usr/bin/env bash
# Deliverable D1: rebuilds demo/repo into the exact state the live demo needs -
# a clean git history plus the AI-authored change sitting as an uncommitted
# working-tree diff, ready for Frictionless's default working-tree mode.
#
# Never hand-edit demo/repo - it is fully regenerated by this script every time.
# To change the demo, edit demo/source/ (the base) or demo/ai-change.patch (the
# AI's change), then rerun this script.
set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$DEMO_DIR/repo"

rm -rf "$REPO_DIR"
mkdir -p "$REPO_DIR"
cp -R "$DEMO_DIR/source/." "$REPO_DIR/"

cd "$REPO_DIR"
git init -q
git -c user.name="Frictionless Demo" -c user.email="demo@example.invalid" add -A
git -c user.name="Frictionless Demo" -c user.email="demo@example.invalid" \
    commit -q -m "Base: transfer service before the AI change"

git apply "$DEMO_DIR/ai-change.patch"

echo "Demo repo ready at: $REPO_DIR"
echo "Base commit is clean; the AI-authored change is sitting as an uncommitted diff."
echo "Open $REPO_DIR in IntelliJ IDEA (Frictionless in working-tree mode) to run the demo."
